esphome:
  name: tubeszb-efr32-mgm24-2023
  project:
    name: tubeszb.efr32_mgm24_2023
    version: "2025.08.22.1"


  min_version: 2025.8.0

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server
  - source: github://tube0013/esphome-components
    components: [uart]
#dashboard_import:
  #package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-efr32-MGM24/firmware/ESPHome/tubeszb-mgm24.yaml

#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12
 
    # Optional manual IP
  #manual_ip:
  #  static_ip: STATIC_IP
  #  gateway: GATEWAY
  #  subnet: SUBNET 

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80
  local: true

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - delay: 5s
      - switch.turn_off: zBSL
   
switch:
  - platform: gpio
    pin: 5
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 16
    name: "Bootloader pin (PA0)"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    disabled_by_default: true  

button:    
  - platform: restart
    name: "Restart the Gateway"
    disabled_by_default: true

  - platform: template
    name: "EFR32 Reset"
    id: zRST
    disabled_by_default: true  
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

  - platform: template
    name: "Trigger MGM24 Module Bootloader"
    disabled_by_default: true
    on_press:
      - script.execute: fw_update_mode

uart:
  id: uart_bus
  rx_pin: GPIO36
  tx_pin: GPIO4
  cts_pin: GPIO13
  rts_pin: GPIO2
  # possible values are
  # - DISABLE = disable hardware flow control
  # - RTS = enable RX hardware flow control (rts)
  # - CTS = enable TX hardware flow control (cts)
  # - CTS_RTS = enable hardware flow control
  # - MAX = ?
  hw_flow_control: CTS_RTS  
  baud_rate: 115200
  rx_buffer_size: 1024


stream_server:
  uart_id: uart_bus
  port: 6638 # optional, default is 6638
  buffer_size: 1024

binary_sensor:
  - platform: stream_server
    connected:
      name: "TubesZB Serial Connected"
sensor:
  - platform: stream_server
    connection_count:
      name: "Connection Count"

mdns:
  services:
    - service: "_zigbee-coordinator"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1
        name: "TubesZB"
        radio_type: "ezsp"
        serial_number: !lambda 'return esphome::get_mac_address();'

text_sensor:
  - platform: template
    name: "ESPHome Project Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address

  - platform: uptime
    name: Uptime
    format:
      separator: " "
      days: "D"

