esphome:
  name: tubeszb-dr-mgm21-22-exp
  project: 
    name: tubezb.mgm21+zw
    version: "2025.10.27.0"
  min_version: 2025.10.0
  on_boot:
    - priority: 600
      then:
        - switch.turn_on: zRST_gpio
        - delay: 15ms
        - switch.turn_off: zRST_gpio
    - priority: -10
      then:
        - delay: 20s
        - component.update: fw_updater

esp32:
  board: esp32-poe
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_PM_ENABLE: "n"
      # Prevent IDF from trying to power-down UART in light sleep, which causes
      # uart_param_config to return ESP_ERR_NOT_SUPPORTED on some targets
      CONFIG_PM_POWER_DOWN_PERIPHERAL_IN_LIGHT_SLEEP: "n"
      CONFIG_UART_ISR_IN_IRAM: "y"

external_components:
  - source: github://oxan/esphome-stream-server
  - source: github://tjhorner/esphome-custom-components
    components: [ project_version ]



#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  
    # Optional manual IP
#  manual_ip:
#    static_ip: STATIC_IP
#    gateway: GATEWAY
#    subnet: SUBNET

# Enable logging
logger:
  level: INFO
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server
  - platform: http_request

http_request:
  
update:
  - platform: http_request
    id: fw_updater
    name: TubesZB Firmware Update
    source: https://tube0013.github.io/TubesZB-ESPHome-Builder/ota_manifests/ota-tubeszb-dr-mgm21-22-exp.json
    update_interval: 12h
    

web_server:
  port: 80
  version: 2
  js_url: "https://tube0013.github.io/TubesZB-ESPHome-Builder/common/www.js"
#  local: true

switch:
  - platform: gpio
    pin: 2
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF


button:    
  - platform: restart
    name: "Restart the Gateway"
    disabled_by_default: true

  - platform: template
    name: "EFR32 Reset"
    id: zRST
    disabled_by_default: true  
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

uart:
  - id: uart_bus_zb
    rx_pin: GPIO5
    tx_pin: GPIO16
    baud_rate: 115200
    rx_buffer_size: 1024
  - id: uart_bus_zw
    rx_pin: GPIO15
    tx_pin: GPIO14
    baud_rate: 115200

zwave_proxy:
  uart_id: uart_bus_zw

stream_server:
  - id: zb
    uart_id: uart_bus_zb
    port: 6638 # optional, default is 6638
    buffer_size: 1024

binary_sensor:
  - platform: stream_server
    stream_server: zb
    connected:
      name: "TubesZB Zigbee Serial Connected"

  - platform: gpio
    pin: 36
    name: "Bootloader pin (PA0)"
    id: zBSL
    disabled_by_default: true  

mdns:
  services:
    - service: "_zigbee-coordinator"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1
        name: "TubesZB"
        radio_type: "ezsp"
        serial_number: !lambda 'return esphome::get_mac_address();'
    - service: "_zwave"
      protocol: "_esphome"
      txt:
        version: 1
        name: "TubesZB"
        serial_number: !lambda 'return esphome::get_mac_address();'
