esphome:
  name: tubeszb-cc2652p7-poe-2023
  project: 
    name: tubezb.cc2652p7-poe-2023
    version: "2025.07.19.5"
  on_boot:
    priority: 600
    then:
      - lambda: |-
          id(mdns0).add_extra_service({ "_zigbee-coordinator", "_tcp", 6638, {{"radio_type", "znp"}, {"name", "TubesZB"},{"serial_number", get_mac_address()}} });
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server


# dashboard_import:
#   package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-cc2652-P7-poe-2023/firmware/esphome/tubeszb-cc2652p7-poe-2023.yaml

#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
  
    # Optional manual IP
  #manual_ip:
  #  static_ip: STATIC_IP
  #  gateway: GATEWAY
  #  subnet: SUBNET 

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: http_request
  - platform: web_server

http_request:
update:
  - platform: http_request
    name: TubesZB ESPHome FW Update
    source: https://tube0013.github.io/TubesZB-ESPHome-Builder/ota_manifests/ota-tubeszb-cc2652p7-poe-2023.json

web_server:
  port: 80


script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc2538-bsl tool now"
      - logger.log: "cc-bsl usage: cc2538-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex"
      
switch:
  - platform: gpio
    pin: 5
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
      
  - platform: gpio
    pin: 16
    name: "Zigbee Module Bootloader Pin"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    disabled_by_default: true

button:
  - platform: restart
    name: "Restart the Device"

  - platform: template
    name: "Zigbee Module Reset"
    disabled_by_default: true
    id: zRST
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

  - platform: template
    name: "Trigger Zigbee Module Bootloader"
    disabled_by_default: true
    on_press:
      - script.execute: fw_update_mode

uart:
  id: uart_bus
  rx_pin: GPIO36
  tx_pin: GPIO4
  baud_rate: 115200
  rx_buffer_size: 1024

stream_server:
  uart_id: uart_bus
  port: 6638 # optional, default is 6638
  buffer_size: 1024


binary_sensor:
  - platform: stream_server
    connected:
      name: "TubesZB Serial Connected"

mdns:
  id: mdns0

text_sensor:
  - platform: template
    name: "ESPHome Project Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address

  - platform: uptime
    name: Uptime
    format:
      separator: " "
      days: "D"