name: ESPHome Static IP Configuration
description: Provide the static IP configuration for your TubesZB device
title: "[ESPHome] New Configuration Request "
labels: esphome
body:
  - type: markdown
    attributes:
      value: |
        ESPHome Static IP Configuration Request
  - type: dropdown
    id: device_name
    attributes:
      label: Device Name
      description: Required - Select the TubesZB device for the firmware
      options: 
        - tubeszb-cc2652p2-poe-2023
        - tubeszb-cc2652p7-poe-2023
        - tubeszb-cc2652p2-poe-2022
        - tubeszb-cc2652p2-ethusb-2023
        - tubeszb-cc2652p2-ethusb-2022
        - tubeszb-dual-radio-kit-cc2652
        - tubeszb-efr32-mgm210-poe-2023
        - tubeszb-efr32-mgm24-2023
        - tubeszb-dual-radio-kit-mgm24
        - tubeszb-zw
      default: 0
    validations:
      required: true
  - type: input
    id: static_ip
    attributes:
      label: Static IP
      description: Provide the static IP for your ESPHome device
      placeholder: 192.168.1.251
    validations:
      required: true
  - type: input
    id: gateway
    attributes:
      label: Gateway
      description: Provide the address of the local network gateway
      placeholder: 192.168.1.1
    validations:
      required: true
  - type: input
    id: subnet
    attributes:
      label: Subnet Mask
      description: "Provide the subnet mask for the local network (Note: CIDR notation is not supported)"
      placeholder: 255.255.255.0
    validations:
      required: true
