name: ESPHome Static IP Configuration
description: Provide the static IP configuration for your TubesZB device
title: "[ESPHome] New Configuration Request "
labels: esphome
body:
  - type: markdown
    attributes:
      value: |
        ESPHome Static IP Configuration Request
  - type: dropdown
    id: device_name
    attributes:
      label: Device_Name
      description: Required - Select the TubesZB device for the firmware
      options: 
        - tubeszb-cc2652p2-poe-2023
        - tubeszb-cc2652p7-poe-2023
        - tubeszb-cc2652p2-poe-2022
        - tubeszb-cc2652p2-ethusb-2023
        - tubeszb-cc2652p2-ethusb-2022
        - tubeszb-dual-radio-kit-cc2652
        - tubeszb-dual-radio-kit-cc2652-experimental
        - tubeszb-efr32-mgm210-poe-2022
        - tubeszb-efr32-mgm210-poe-2023
        - tubeszb-efr32-mgm24-2023
        - tubeszb-dual-radio-kit-mgm24
        - tubeszb-dual-radio-kit-mgm24-experimental
        - tubeszb-dual-radio-kit-mgm21-2022
        - tubeszb-dual-radio-mgm21-2022-experimental
        - tubeszb-zw
      default: 0
    validations:
      required: true
  - type: input
    id: static_ip
    attributes:
      label: Static_IP
      description: Provide the static IP for your ESPHome device
    validations:
      required: true
  - type: input
    id: gateway
    attributes:
      label: Gateway
      description: Provide the gateway for your ESPHome device
    validations:
      required: true
  - type: input
    id: subnet
    attributes:
      label: Subnet
      description: Provide the subnet for your ESPHome device
    validations:
      required: true
