name: ESPHome Configuration
description: Provide the static IP configuration for your TubesZB device
title: "[ESPHome] New Configuration Request "
labels: esphome
body:
  - type: markdown
    attributes:
      value: |
        ESPHome Static IP Configuration Request
  - type: dropdown
    id: device_name
    label: Device
    attributes:
      label: Device
      description: Select the device name for your TubesZB device
      options: 
        - tubeszb-cc2652p2-poe-2023
        - tubeszb-cc2652p7-poe-2023
        - tubeszb-cc2652p2-poe-2022
        - tubeszb-cc2652p2-ethusb-2023
        - tubeszb-cc2652p2-ethusb-2022
        - tubeszb-zw
      default: 0
    validations:
      required: true
  - type: input
    id: static_ip
    attributes:
      label: Static_IP
      description: Provide the static IP for your ESPHome device
    validations:
      required: true
  - type: input
    id: gateway
    attributes:
      label: Gateway
      description: Provide the gateway for your ESPHome device
    validations:
      required: true
  - type: input
    id: subnet
    attributes:
      label: Subnet
      description: Provide the subnet for your ESPHome device
    validations:
      required: true
