esphome:
  on_boot:
    - priority: 145
      then:
        - if:
            condition:
              switch.is_on: zigbee_fw_beta_switch
            then:
              - lambda: 'id(efr32_manifest_url_default) = "${zigbee_beta_manifest_url}";'
              - logger.log:
                  format: "Boot: Zigbee FW channel restored to BETA"
                  level: INFO

switch:
  - platform: template
    name: "Beta Zigbee Firmware Channel"
    id: zigbee_fw_beta_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    icon: mdi:beta
    web_server:
      sorting_group_id: zigbee_control_group
      sorting_weight: 70
    turn_on_action:
      - lambda: 'id(efr32_manifest_url_default) = "${zigbee_beta_manifest_url}";'
      - script.execute:
          id: apply_efr32_fw_url
          url_str: !lambda 'return id(efr32_custom_fw_url).state;'
      - logger.log:
          format: "Zigbee firmware channel: BETA"
          level: INFO
    turn_off_action:
      - lambda: 'id(efr32_manifest_url_default) = "${zigbee_stable_manifest_url}";'
      - script.execute:
          id: apply_efr32_fw_url
          url_str: !lambda 'return id(efr32_custom_fw_url).state;'
      - logger.log:
          format: "Zigbee firmware channel: STABLE"
          level: INFO
