esphome:
  name: tubeszb-zw
  project: 
    name: tubezb.zw2026
    version: "2025.09.19"

  min_version: 2025.8.0

esp32:
  board: esp32-poe
  framework:
    type: esp-idf

external_components:
  - source: github://oxan/esphome-stream-server

#dashboard_import:
#  package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-zw-kit/tubeszb-zw.yaml

#Olimex ESP32-PoE Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO17
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12
  
    # Optional manual IP
  manual_ip:
    static_ip: STATIC_IP
    gateway: GATEWAY
    subnet: SUBNET

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server

web_server:
  port: 80


button:
  - platform: restart
    name: "Restart the ESP32 Device"

uart:
  id: uart_bus
  rx_pin: GPIO15
  tx_pin: GPIO14
  baud_rate: 115200
  rx_buffer_size: 1024

stream_server:
  buffer_size: 1024
  uart_id: uart_bus
#  id: ss
  port: 6638 # optional, default is 6638

binary_sensor:
  - platform: stream_server
    connected:
      name: "TubesZB ZW Serial Connected"

mdns:
  services:
    - service: "_zwave"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1
        name: "TubesZB"
        serial_number: !lambda 'return esphome::get_mac_address();'

text_sensor:
  - platform: template
    name: "ESPHome Project Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address

  - platform: uptime
    name: Uptime
    format:
      separator: " "
      days: "D"