esphome:
  name: tubeszb-cc2652p2-ethusb-2022
  project: 
    name: tubeszb.cc2652p2-ethusb-2022
    version: "2025.09.20.0"
  min_version: 2025.8.0
  on_boot:
    - priority: 600
      then:
        - switch.turn_on: zRST_gpio
        - delay: 15ms
        - switch.turn_off: zRST_gpio
    - priority: -10
      then:
        - delay: 20s
        - component.update: fw_updater

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_PM_ENABLE: "n"
      # Prevent IDF from trying to power-down UART in light sleep, which causes
      # uart_param_config to return ESP_ERR_NOT_SUPPORTED on some targets
      CONFIG_PM_POWER_DOWN_PERIPHERAL_IN_LIGHT_SLEEP: "n"
      CONFIG_UART_ISR_IN_IRAM: "y"


external_components:
  - source: github://oxan/esphome-stream-server
  - source: github://tjhorner/esphome-custom-components
    components: [ project_version ]

# dashboard_import:
#   package_import_url: github://tube0013/tube_gateways/models/current/tubeszb-cc2652-eth_usb/firmware/esphome/tubezb-cc2652p2-ethusb-2022.yaml

#WT32-ETH01 Ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin: GPIO0
    mode: CLK_EXT_IN
  phy_addr: 1
  power_pin: GPIO16

    # Optional manual IP
  manual_ip:
    static_ip: STATIC_IP
    gateway: GATEWAY
    subnet: SUBNET 

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server
  - platform: http_request

http_request:
  
update:
  - platform: http_request
    id: fw_updater
    name: TubesZB Firmware Update
    source: https://tube0013.github.io/TubesZB-ESPHome-Builder/ota_manifests/ota-tubeszb-cc2652p2-ethusb-2022.json
    update_interval: 12h
    


web_server:
  port: 80
  version: 2
  js_url: "https://tube0013.github.io/TubesZB-ESPHome-Builder/common/www.js"


script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
      - delay: 1s
      - switch.turn_off: zRST_gpio
    - priority: -10
      then:
        - delay: 20s
        - component.update: fw_updater
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc2538-bsl tool now"
      - logger.log: "cc-bsl usage: cc2538-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex"
      
switch:
  - platform: gpio
    pin: 33
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
      
  - platform: gpio
    pin: 32
    name: "zBSL"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    
  - platform: template
    name: "Prep the cc2652p2 for firmware update"
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - button.press: zRST

button:
  - platform: restart
    name: "Restart the Device"

  - platform: template
    name: "Zigbee Module Reset"
    id: zRST
    on_press:
      - switch.turn_on: zRST_gpio
      - delay: 15ms
      - switch.turn_off: zRST_gpio

uart:
  id: uart_bus
  rx_pin: GPIO17
  tx_pin: GPIO5
  baud_rate: 115200
  rx_buffer_size: 1024

stream_server:
  uart_id: uart_bus
  id: ss
  port: 6638 # optional, default is 6638
  buffer_size: 1024

binary_sensor:
  - platform: stream_server
    connected:
      name: "TubesZB Serial Connected"

mdns:
  services:
    - service: "_zigbee-coordinator"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1
        name: "TubesZB"
        radio_type: "znp"
        serial_number: !lambda 'return esphome::get_mac_address();'

text_sensor:
  - platform: project_version
    name: "TubesZB Device Firmware Version"
    internal: true

  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP MAC Address

  - platform: uptime
    name: Uptime
    format:
      separator: " "
      days: "D"