esphome:
  name: tubeszb-zw-experimental
  project:
    name: tubezb.zwexp
    version: ${project_version}
  min_version: 2026.3.2

packages:
  version: !include ../common/version.yaml
  esp_idf: !include
    file: ../common/esp_idf.yaml
    vars:
      board: esp32-poe
  ethernet: !include
    file: ../common/ethernet_olimex_static.yaml
    vars:
      static_ip: STATIC_IP
      gateway: GATEWAY
      subnet: SUBNET
  base: !include ../common/base_static.yaml
  device_info: !include ../common/device_info.yaml
  web_server: !include ../common/web_server_simple.yaml

script:
  - id: run_update_checks
    then:
      - logger.log: "Internet confirmed. No ESPHome self-update is configured for static IP builds."

button:
  - platform: restart
    name: "Restart the Device"
    icon: mdi:restart
    web_server:
      sorting_group_id: device_control_group
      sorting_weight: 10

uart:
  id: uart_bus
  rx_pin: GPIO16
  tx_pin: GPIO5
  baud_rate: 115200
  rx_buffer_size: 1024

zwave_proxy:
  uart_id: uart_bus

mdns:
  services:
    - service: "_zwave"
      protocol: "_esphome"
      txt:
        version: 1
        name: "TubesZB"
        serial_number: !lambda 'return esphome::get_mac_address();'
